FROM debian:latest

ENV USER administrateur

WORKDIR /root
RUN apt update && apt upgrade -y
RUN apt install python3 ansible python3-ansible-runner python3-flask gunicorn3 git -y
RUN apt clean && apt autoremove
RUN git clone https://github.com/Yoyox78/Site_Deploiement_Logiciels 

WORKDIR /root/Site_Deploiement_Logiciels 
RUN mv Full_independant /etc/Deploiement_Logiciel
WORKDIR /root/
RUN rm -rf Site_Deploiement_Logiciels 

RUN mkdir /root/.ssh/
COPY id_* /root/.ssh/
RUN chmod 600 /root/.ssh/id_*
RUN sed -i "s@useradm = \"USRADM\"@useradm = os.environ.get('USER', 'default_value')@" /etc/Deploiement_Logiciel/app.py

EXPOSE 80
WORKDIR /etc/Deploiement_Logiciel
ENTRYPOINT /usr/bin/gunicorn -w 1 -b 0.0.0.0:80 --timeout 600 app:app

