FROM alpine:latest

ENV USER administrateur

WORKDIR /root

RUN apk update && apk upgrade

RUN apk add python3 py3-pip py3-gunicorn ansible-core unzip py3-flask

RUN pip install ansible-runner --break-system-packages

ADD https://github.com/Yoyox78/Site_Deploiement_Logiciels/archive/refs/heads/main.zip /root/main.zip

RUN unzip /root/main.zip -d /root/

WORKDIR /root/Site_Deploiement_Logiciels-main 
RUN mv Full_independant /etc/Deploiement_Logiciel

WORKDIR /root/
RUN rm -rf Site_Deploiement_Logiciels* main.zip

RUN mkdir /root/.ssh/
COPY id_* /root/.ssh/
RUN chmod 600 /root/.ssh/id_*
RUN sed -i "s@useradm = \"USRADM\"@useradm = os.environ.get('USER', 'default_value')@" /etc/Deploiement_Logiciel/app.py

EXPOSE 80
WORKDIR /etc/Deploiement_Logiciel
ENTRYPOINT /usr/bin/gunicorn -w 1 -b 0.0.0.0:80 --timeout 600 app:app

